#include"trade.h"
#include<string.h>
#include"common.h"

// Trading places.
Trader g_trader[MAX_TRADER_COUNT];
int g_minimum_starting_items;

// A single node on the solution graph.
typedef struct
{
   // Unordered set of items, encoded as an array of item counts indexed
   // by item ID.  This node is viable if player hold items that are
   // at or exceed each entry in item_count.
   //
   // This only needs to count up to MAX_ITEM_ID+1, since we don't need
   // to track GOAL_ITEM_ID in the solution path.
   uint8_t item_count[MAX_ITEM_ID + 1];

   // Trader statuses, using same index as g_trader.
   // 1 = a trade must have not taken place with the indexed trader
   //     for the player to follow this node.
   // 0 = a trade may or may not have taken place with the indexed
   //     trader, i.e. viability of current node is independent of
   //     status of the indexed trader.
   //
   // When building the known solution path, we start from the root
   // (goal) and expand outward, so the traders are marked with whether
   // they will be used later in the solution path when the nodes are
   // closers to the root.
   uint8_t trader_reserved[MAX_TRADER_COUNT];

   // If this node is viable, player should make the next trade with
   // the trader indexed at next_move.
   int next_move;
} TradeNode;

// Known solution path, generated by InitTraders.  This is not
// necessarily the shortest solution path, just one that is guaranteed
// to work.
//
// Size is fixed at MAX_TRADER_COUNT, since the generated solution
// only requires making at most one trade per trader.
static TradeNode g_known_solution[MAX_TRADER_COUNT];
static int g_known_solution_path_length;

// If player diverged from the known solution path, FindNextTrader will
// try to find a recovery path back to the known solution.  If that
// search is successful, the result will be cached here.
//
// This is not merely a time saving measure -- due to subtleties in
// how the trader statues are tracked, we can't always reproduce the
// same path after having walked a few steps along it.  So, we save
// the last path we computed, and recompute the recovery path only if
// the player has strayed off of the recovery path.
static TradeState g_recovery_path[MAX_TRADER_COUNT * 2];
static int g_recovery_path_size;

// Check if a tentative circular shape will overlap with any existing
// objects, returns nonzero value if there will be an overlap.
static int CheckForOverlap(int trader_count, int x, int y, int r)
{
   const int trader_distance_2 =
      (TRADER_SEPARATION / 2 + r) * (TRADER_SEPARATION / 2 + r);
   const int sign_distance_2 = (SIGN_RADIUS + r) * (SIGN_RADIUS + r);
   for(int i = 0; i < trader_count; i++)
   {
      const Trader *t = &g_trader[i];
      const int tdx = x - t->position.x;
      const int tdy = y - t->position.y;
      if( tdx * tdx + tdy * tdy < trader_distance_2 )
         return 1;
      for(int j = 0; j < t->sign_count; j++)
      {
         const int sdx = x - t->sign[j].x;
         const int sdy = y - t->sign[j].y;
         if( sdx * sdx + sdy * sdy < sign_distance_2 )
            return 1;
      }
   }
   return 0;
}

// Check if item is on the request list, returns 1 if so.
static int IsRequested(int trader_index, int item_id)
{
   assert(trader_index >= 0);
   assert(trader_index < MAX_TRADER_COUNT);
   for(int i = 0; i < g_trader[trader_index].request_count; i++)
   {
      if( g_trader[trader_index].requests[i] == item_id )
         return 1;
   }
   return 0;
}

// Check if item is on the offer list, returns 1 if so.
static int IsOffered(int trader_index, int item_id)
{
   assert(trader_index >= 0);
   assert(trader_index < MAX_TRADER_COUNT);
   for(int i = 0; i < g_trader[trader_index].offer_count; i++)
   {
      if( g_trader[trader_index].offers[i] == item_id )
         return 1;
   }
   return 0;
}

// Add item to offer list.
static void AddOffer(int trader_index, int item_id)
{
   assert(trader_index >= 0);
   assert(trader_index < MAX_TRADER_COUNT);
   assert(g_trader[trader_index].offer_count < MAX_TRANSACTION_SIZE);
   g_trader[trader_index].offers[g_trader[trader_index].offer_count++] =
      item_id;
}

// Add item to request list.
static void AddRequest(int trader_index, int item_id)
{
   assert(trader_index >= 0);
   assert(trader_index < MAX_TRADER_COUNT);
   assert(g_trader[trader_index].request_count < MAX_TRANSACTION_SIZE);
   g_trader[trader_index].requests[g_trader[trader_index].request_count++] =
      item_id;
}

// Check if newly added trader overlaps with the origin or any previously
// added traders, returns 1 if so.
static int LastTraderOverlapsWithEarlier(int last_index)
{
   const int x = g_trader[last_index].position.x;
   const int y = g_trader[last_index].position.y;
   if( x * x + y * y < TRADER_SEPARATION * TRADER_SEPARATION )
      return 1;
   for(int i = 0; i < last_index; i++)
   {
      const int dx = g_trader[i].position.x - x;
      const int dy = g_trader[i].position.y - y;
      if( dx * dx + dy * dy < TRADER_SEPARATION * TRADER_SEPARATION )
         return 1;
   }
   return 0;
}

// Populate trader position fields.
//
// This works by choosing random coordinates for each trader until we
// find one without overlap, expanding the random range at each step
// so that we don't run out of options.
static void InitTraderPositions(int trader_count)
{
   assert(trader_count >= 3);
   assert(trader_count <= MAX_TRADER_COUNT);

   // Quantize random range at this many pixels.
   //
   // This quantization is done because generating random numbers for
   // a larger range tend to result in less random numbers on systems
   // with a low RAND_MAX.
   #define GRID_UNIT    8

   int range = TRADER_SEPARATION / GRID_UNIT;
   for(int i = 0; i < trader_count; i++)
   {
      // Generate coordinates inside a bounding box, slowly increasing
      // the bounding box size if we failed to pick a coordinate without
      // overlaps.  The intent is to cluster traders together.
      for(;; range++)
      {
         g_trader[i].position.x = RAND_RANGE(-range, range) * GRID_UNIT;
         g_trader[i].position.y = RAND_RANGE(-range, range) * GRID_UNIT;

         // Stop when the newly generated trader does not overlap.
         if( !LastTraderOverlapsWithEarlier(i) )
            break;
      }
   }
}

// Place sign for a single trader.
static void PlaceSign(int trader_count, int selected_trader, int direction)
{
   Trader *t = &(g_trader[selected_trader]);
   XY *s = &(t->sign[t->sign_count]);
   for(int attempt = 0; attempt < 4; attempt++)
   {
      // Place the sign at some random distance away from the trader,
      // always aligned on one axis.
      switch( direction )
      {
         case 0:  // Below trader, pointing up.
            s->x = t->position.x;
            s->y = t->position.y + RAND_RANGE(TRADER_SEPARATION,
                                              TRADER_SEPARATION * 2);
            break;
         case 1:  // Above trader, pointing down.
            s->x = t->position.x;
            s->y = t->position.y - RAND_RANGE(TRADER_SEPARATION,
                                              TRADER_SEPARATION * 2);
            break;
         case 2:  // To the right of trader, pointing left.
            s->x = t->position.x + RAND_RANGE(TRADER_SEPARATION,
                                              TRADER_SEPARATION * 2);
            s->y = t->position.y;
            break;
         case 3:  // To the left of trader, pointing right.
            s->x = t->position.x - RAND_RANGE(TRADER_SEPARATION,
                                              TRADER_SEPARATION * 2);
            s->y = t->position.y;
            break;
      }
      if( !CheckForOverlap(trader_count, s->x, s->y, SIGN_RADIUS) )
      {
         t->sign_count++;
         return;
      }
   }
}

// Populate trader sign fields.
static void InitSignPositions(int trader_count)
{
   // Keep track of directions for which we have already placed signs for,
   // one byte per trader, one bit per direction.
   uint8_t used_direction[MAX_TRADER_COUNT];
   memset(used_direction, 0, sizeof(used_direction));

   for(int i = 0; i < trader_count * MAX_SIGN_COUNT; i++)
   {
      // Select a random trader.
      //
      // Note that we skip over 0, which means the goal trader will
      // never get any directional signs.
      int selected_trader = RAND_RANGE(1, trader_count - 1);
      if( g_trader[selected_trader].sign_count == MAX_SIGN_COUNT )
         continue;

      // Choose a direction that we haven't yet placed sign for.
      int direction = RAND_RANGE(0, 3);
      for(int j = 0; j < 4; j++)
      {
         if( (used_direction[selected_trader] & (1 << direction)) == 0 )
         {
            // Attempt to place the sign.
            PlaceSign(trader_count, selected_trader, direction);

            // The attempt to place sign may or may not be successful, but
            // we will mark the direction as used either way.  This is so
            // that if we can't place a sign for a particular direction
            // (probably because it was too crowded), we won't try again.
            used_direction[selected_trader] |= (1 << direction);
            break;
         }
         direction = (direction + 1) & 3;
      }
   }
   assert(g_trader[0].sign_count == 0);
}

// Check if a node is the starting node of the solution path, returns 1 if so.
static int ReachedStartingNode(const TradeNode *node)
{
   for(int i = STARTING_ITEM_ID + 1; i <= MAX_ITEM_ID; i++)
   {
      if( node->item_count[i] > 0 )
         return 0;
   }
   return 1;
}

// Recursively generate solution path, returns 0 if branch is not viable.
//
// This is essentially a depth-first search from goal node to starting
// node.  This being a depth-first search and not a breadth-first
// search meant the solution is not guaranteed to be optimal, but we
// already know the solution might not be optimal when we didn't take
// the distraction nodes into account.
//
// The reason why we are not doing breadth-first search over all nodes
// is because upper bound in the number of search nodes is
// proportional to the factorial of number of traders, and we just
// don't have that much memory.
static int InitKnownSolution(int trader_count, int path_length, int cursor)
{
   // Build trading state before making the trade at g_trader[cursor].
   TradeNode *node = &g_known_solution[path_length];
   if( LIKELY(cursor > 0) )
   {
      memcpy(node, &g_known_solution[path_length - 1], sizeof(TradeNode));
      for(int i = 0; i < g_trader[cursor].offer_count; i++)
      {
         // While traversing backwards on the solution path, each node
         // contain items that are obtained from the "offer" list of
         // each trader.  So current node offering more of some item
         // than what the parent node has is an indication that
         // current node should not be on the solution path.
         const int item_index = g_trader[cursor].offers[i];
         if( node->item_count[item_index] == 0 )
            return 0;
         node->item_count[item_index]--;
      }
   }
   for(int i = 0; i < g_trader[cursor].request_count; i++)
      node->item_count[g_trader[cursor].requests[i]]++;

   // Stop when we have completed the path.
   if( ReachedStartingNode(node) )
   {
      node->next_move = cursor;
      g_known_solution_path_length = path_length + 1;
      return 1;
   }

   // Mark current node as reserved, so it will not be visited again
   // along the solution path.
   assert(node->trader_reserved[cursor] == 0);
   node->trader_reserved[cursor] = 1;

   // Check child nodes.
   for(int i = 0; i < trader_count; i++)
   {
      if( node->trader_reserved[i] != 0 || g_trader[i].offer_count == 0 )
         continue;
      if( InitKnownSolution(trader_count, path_length + 1, i) )
      {
         node->next_move = cursor;
         assert(g_known_solution_path_length > path_length);
         return 1;
      }
   }

   // Path using current node is not viable.
   return 0;
}

#ifndef NDEBUG
// Check that the offers list and requests list do not overlap.
// Returns 1 if list looks fine.
static int CheckNoOverlap(int trader_index)
{
   for(int i = 0; i < g_trader[trader_index].request_count; i++)
   {
      for(int j = 0; j < g_trader[trader_index].offer_count; j++)
      {
         if( g_trader[trader_index].requests[i] ==
             g_trader[trader_index].offers[j] )
         {
            return 0;
         }
      }
   }
   return 1;
}
#endif

// Initialize trading graph.
void InitTraders(int trader_count)
{
   assert(trader_count >= 3);
   assert(trader_count <= MAX_TRADER_COUNT);

   memset(g_trader, 0, sizeof(g_trader));
   g_minimum_starting_items = 0;

   // Initialize goal.
   AddOffer(0, GOAL_ITEM_ID);

   // Use maximum transaction size only in hard mode, otherwise limit
   // the number of requests/offers at each trading place to 3.
   assert(3 <= MAX_TRANSACTION_SIZE);
   const int transaction_limit =
      trader_count == MAX_TRADER_COUNT ? MAX_TRANSACTION_SIZE : 3;

   // Perform random traversals from goal to leaf, and add offer/request
   // pairs at each node.  This works so that the goal can be attained by
   // trading items from leaf to root.
   //
   // If we only do exactly one traversal, we get a linked list with exactly
   // one solution, which seems boring, so we do multiple traversals and
   // layer the paths on top of each other.  The result is that the root is
   // attainable if player does some type of reverse breadth-first search,
   // collecting dependent items from nodes that are further away from the
   // root to trade with items that are closer to the root.
   //
   // As a side effect of layering multiple traversals:
   //
   // - It's not guaranteed that player now needs to visit every leaf node
   //   to reach the root, since some dependencies may be satisfied via
   //   accidental overlaps in offered items.  So this algorithm guarantees
   //   that a solution exists, but doesn't guarantee that the generated
   //   solution is optimal.
   //
   // - Because player may visit a shallower node that accepts the same
   //   requests as a deeper node, but the shallower node might not have all
   //   the offers needed to satisfy upstream dependencies, an incorrect
   //   visit order may cause the player to get stuck.  For this reason, we
   //   allow trades to be reversed at any node so that players can undo
   //   their mistakes.
   //
   // - Since it's possible to undo mistakes, we also insert distraction
   //   nodes that are not on any of the generated traversal paths, for
   //   variety.  Although these are distraction nodes, there is some chance
   //   that what they offer might actually lead to a shorter path.
   uint8_t used_items[MAX_ITEM_ID + 1];
   while( g_trader[0].request_count < transaction_limit )
   {
      memset(used_items, 0, sizeof(used_items));
      int cursor = 0;
      for(;;)
      {
         // Select the next trader in the traversal chain.  Because the
         // selection always happens in one direction, we guarantee no
         // loops in this chain.
         //
         // We stop when the next step would request a trader that is
         // at the requested size, such that we reserve at least one
         // trader to serve as distraction node.
         const int step = RAND_RANGE(1, 5);
         if( cursor + step >= trader_count - 1 )
            break;
         const int next = cursor + step;

         // Terminate chain if next trader no longer has capacity to offer
         // or request any more items.
         if( g_trader[next].offer_count >= transaction_limit ||
             g_trader[next].request_count >= transaction_limit )
         {
            break;
         }

         // Choose an item that has not yet been requested on this chain,
         // and add it to the request for the current node.
         //
         // Also, to avoid self loops:
         // - Avoid requesting item requested by downstream trader.
         // - Avoid requesting item that the current node offers.
         int item_id = RAND_RANGE(STARTING_ITEM_ID + 1, MAX_ITEM_ID);
         for(int i = 0;
             (used_items[item_id] ||
              IsRequested(next, item_id) ||
              IsOffered(cursor, item_id)) &&
             i < MAX_ITEM_ID;
             i++)
         {
            item_id++;
            if( item_id > MAX_ITEM_ID )
               item_id = STARTING_ITEM_ID + 1;
         }
         if( used_items[item_id] ||
             IsRequested(next, item_id) ||
             IsOffered(cursor, item_id) )
         {
            break;
         }
         used_items[item_id] = 1;

         // Add node to chain.
         AddRequest(cursor, item_id);
         AddOffer(next, item_id);
         assert(CheckNoOverlap(cursor));
         cursor = next;
      }

      // Add starting item to leaf node.
      AddRequest(cursor, STARTING_ITEM_ID);
      assert(CheckNoOverlap(cursor));

      // Update required item count for each leaf node.  Note that this is
      // not done for any of the distraction nodes.
      g_minimum_starting_items++;
   }

   // Reset solution state.
   //
   // We need to zero out g_known_solution because some parts of
   // InitKnownSolution tracks state in those array cells before
   // updating g_known_solution_path_length.
   //
   // We don't need to zero out g_recovery_path because g_recovery_path_size
   // is always updated together with the writes, so we have removed
   // the call to memset for that, even though it doesn't result in
   // any measurable performance difference.
   memset(g_known_solution, 0, sizeof(g_known_solution));
   g_known_solution_path_length = 0;
   g_recovery_path_size = 0;

   // Generate solution path before adding distractions.
   InitKnownSolution(trader_count, 0, 0);
   assert(g_known_solution_path_length > 0);

   // Populate distraction nodes.
   for(int i = 0; i < trader_count; i++)
   {
      if( g_trader[i].request_count > 0 )
         continue;

      // Choose a random downstream node and copy some of their offers.
      const int next =
         i + 1 < trader_count ? RAND_RANGE(i + 1, trader_count - 1) : i;
      if( next != i )
      {
         const int copy_count = RAND(g_trader[next].offer_count);
         if( copy_count > 0 )
         {
            for(int j = 0; j < copy_count; j++)
               g_trader[i].requests[j] = g_trader[next].offers[j];
            g_trader[i].request_count = copy_count;
         }
      }
      if( g_trader[i].request_count == 0 )
         AddRequest(i, STARTING_ITEM_ID);

      // Offer random items.
      int max_offer_count = RAND_RANGE(1, transaction_limit);
      for(int j = 0; j < max_offer_count; j++)
      {
         int item_id = RAND_RANGE(STARTING_ITEM_ID + 1, MAX_ITEM_ID);
         for(int k = 0; IsRequested(i, item_id) && k < MAX_ITEM_ID; k++)
         {
            item_id++;
            if( item_id > MAX_ITEM_ID )
               item_id = STARTING_ITEM_ID + 1;
         }
         if( IsRequested(i, item_id) )
            break;
         AddOffer(i, item_id);
      }
      assert(CheckNoOverlap(i));
   }

   InitTraderPositions(trader_count);
   InitSignPositions(trader_count);
}

// Check if current game state satisfies a single known solution node,
// returns 1 if so.
static int PassesRequirements(int trader_count,
                              const TradeState *state,
                              const TradeNode *node)
{
   for(int i = STARTING_ITEM_ID; i <= MAX_ITEM_ID; i++)
   {
      if( state->item_count[i] < node->item_count[i] )
         return 0;
   }
   for(int i = 0; i < trader_count; i++)
   {
      if( node->trader_reserved[i] != 0 && state->traded[i] != 0 )
         return 0;
   }
   return 1;
}

// Check if current game state satisfies any state on the solution
// path.  If so, return index of the next trader that player should
// trade with, otherwise return -1.
static int CheckKnownSolutionPath(int trader_count, const TradeState *state)
{
   TradeNode *node = g_known_solution;
   for(int i = 0; i < g_known_solution_path_length; i++, node++)
   {
      if( PassesRequirements(trader_count, state, node) )
         return node->next_move;
   }
   return -1;
}

// Check if current game state matches the precomputed nodes on the
// recovery path.  If so, return index of the next trader that the
// player should trade with, otherwise return -1.
static int CheckRecoveryPath(const TradeState *state)
{
   TradeState *node = g_recovery_path;
   for(int i = 0; i < g_recovery_path_size; i++, node++)
   {
      // Unlike CheckKnownSolutionPath, here the state must match exactly,
      // since any deviation meant the computed path is now stale.
      if( memcmp(state->item_count,
                 node->item_count,
                 sizeof(node->item_count)) == 0 &&
          memcmp(state->traded,
                 node->traded,
                 sizeof(node->traded)) == 0 )
      {
         return node->trader_index;
      }
   }
   return -1;
}

// Prepare next search state after performing trade with trader.
// Returns 0 if trade can not be performed.
static int GetNextStateAfterTrade(
   const TradeState *state, int trader_index, TradeState *next)
{
   assert(trader_index >= 0);
   assert(trader_index < MAX_TRADER_COUNT);
   const Trader *t = &(g_trader[trader_index]);

   memcpy(next, state, sizeof(TradeState));
   if( state->traded[trader_index] )
   {
      // Player needs same or more items than what's in the offer list
      // to undo the trade.
      for(int i = 0; i < t->offer_count; i++)
      {
         const int item_id = t->offers[i];
         assert(item_id <= GOAL_ITEM_ID);
         if( next->item_count[item_id] == 0 )
            return 0;
         next->item_count[item_id]--;
      }
      for(int i = 0; i < t->request_count; i++)
      {
         const int item_id = t->requests[i];
         assert(item_id <= GOAL_ITEM_ID);
         next->item_count[item_id]++;
      }
      next->traded[trader_index] = 0;
   }
   else
   {
      // Player needs same or more items than what's in the request list
      // to perform the trade.
      for(int i = 0; i < t->request_count; i++)
      {
         const int item_id = t->requests[i];
         assert(item_id <= GOAL_ITEM_ID);
         if( next->item_count[item_id] == 0 )
            return 0;
         next->item_count[item_id]--;
      }
      for(int i = 0; i < t->offer_count; i++)
      {
         const int item_id = t->offers[i];
         assert(item_id <= GOAL_ITEM_ID);
         next->item_count[item_id]++;
      }
      next->traded[trader_index] = 1;
   }

   next->trader_index = trader_index;
   return 1;
}

// Check if current state can reach a node on the known solution path.
// Returns index of the next trader that the player should trade with
// if solution is possible, otherwise return -1.
static int FindWayToKnownSolution(
   int trader_count, const TradeState *state, int *visit_count, int depth)
{
   // Give up upon reaching maximum depth.
   if( depth > trader_count )
      return -1;

   // If current state is on the known solution path, we can return
   // the next move from precomputed path.
   const int t = CheckKnownSolutionPath(trader_count, state);
   if( t >= 0 )
      return t;

   // Perform depth-first search to reach known solution path.
   TradeState child_state;
   for(int pass = 0; pass < 2; pass++)
   {
      for(int i = 0; i < trader_count; i++)
      {
         // We shouldn't have to visit the same trader more than twice,
         // once for undo and once to make the proper trade.
         if( visit_count[i] >= 2 )
            continue;

         // Do not undo the last trade that got us here.
         if( i == state->trader_index )
            continue;

         // Prefer to undo trades in the first pass, and attempt new
         // trades in the second pass.
         if( (pass ^ state->traded[i]) == 0 )
            continue;

         // Check if solution is reachable after performing a trade.
         // If so, player's next move should be to trade with this trader.
         if( !GetNextStateAfterTrade(state, i, &child_state) )
            continue;
         visit_count[i]++;
         if( FindWayToKnownSolution(
                trader_count, &child_state, visit_count, depth + 1) >= 0 )
         {
            // Cache recovery path.
            assert(g_recovery_path_size < MAX_TRADER_COUNT * 2);
            memcpy(&(g_recovery_path[g_recovery_path_size]),
                   state,
                   sizeof(TradeState));
            g_recovery_path[g_recovery_path_size].trader_index = i;
            g_recovery_path_size++;
            return i;
         }
         visit_count[i]--;
      }
   }

   // No solution.
   return -1;
}

// Return index of the next trader that the player should attempt to trade with.
int FindNextTrader(int trader_count, const TradeState *state)
{
   // If player is currently on the known solution path, we can return
   // the next step from there.
   const int t1 = CheckKnownSolutionPath(trader_count, state);
   if( t1 >= 0 )
      return t1;

   // Player has strayed off of the known solution path, but if we
   // have previously computed a recovery path and player is still on
   // that, we can return the next step from there.
   const int t2 = CheckRecoveryPath(state);
   if( t2 >= 0 )
      return t2;

   // Need to recompute the recovery path.
   g_recovery_path_size = 0;
   int visit_count[MAX_TRADER_COUNT];
   memset(visit_count, 0, sizeof(visit_count));
   return FindWayToKnownSolution(trader_count, state, visit_count, 0);
}

// Get range of coordinates occupied by traders.
void GetTraderRange(int trader_count, XY *min, XY *max)
{
   min->x = max->x = g_trader[0].position.x;
   min->y = max->y = g_trader[0].position.y;
   for(int i = 1; i < trader_count; i++)
   {
      if( min->x > g_trader[i].position.x ) min->x = g_trader[i].position.x;
      if( min->y > g_trader[i].position.y ) min->y = g_trader[i].position.y;
      if( max->x < g_trader[i].position.x ) max->x = g_trader[i].position.x;
      if( max->y < g_trader[i].position.y ) max->y = g_trader[i].position.y;
   }
}

// Update list of landmark positions.
//
// This is done by walking the world on a hexagonal grid, expand outwards
// from the center on a spiral path until we got enough positions to hold
// all landmarks.
//
// The spiral path allows us to place landmarks more near the center.  An
// alternative way to place landmarks would be to just generate random
// coordinates until we found enough without overlaps, using the same
// algorithm as InitTraderPositions.  But the result from that tend to
// concentrate the landmarks near the edges, even if there are empty lots
// near the center where landmarks would fit.  By testing each position
// starting from the center, landmarks that can fit near the center would
// generally be placed near the center.
//
// Because we can't exhaustively test all positions, we test positions
// following a grid pattern.  Using a rectangular grid results in vertical
// overlaps that don't look nice, so we use a hexagonal grid.
void GetLandmarkPositions(int trader_count, XY *landmark_positions)
{
   // Compute offset steps for walking the grid.  This is not static even
   // though all values can be computed at compile time.  This is so that
   // the offsets array live on the stack during the generation process.
   #define SQRT3  1.7320508075688772f
   assert(LANDMARK_RADIUS > 0);
   const XY offset[6] =
   {
      {-LANDMARK_RADIUS,      (int)(LANDMARK_RADIUS * SQRT3)},
      {-LANDMARK_RADIUS * 2,  0},
      {-LANDMARK_RADIUS,      -(int)(LANDMARK_RADIUS * SQRT3)},
      {LANDMARK_RADIUS,       -(int)(LANDMARK_RADIUS * SQRT3)},
      {LANDMARK_RADIUS * 2,   0},
      {LANDMARK_RADIUS,       (int)(LANDMARK_RADIUS * SQRT3)},
   };
   #undef SQRT3

   // Reserved region near the origin.  This is to avoid obscuring the
   // player's starting position with landmarks.
   #define RESERVED_MIN_X  (-SCREEN_WIDTH / 2 - LANDMARK_RADIUS)
   #define RESERVED_MIN_Y  (-SCREEN_HEIGHT / 2 - LANDMARK_RADIUS)
   #define RESERVED_MAX_X  (SCREEN_WIDTH / 2 + LANDMARK_RADIUS)
   #define RESERVED_MAX_Y  (SCREEN_HEIGHT / 2 + LANDMARK_RADIUS)

   // Tentative landmark positions.  We will generate some valid positions
   // first, shuffle those, then assign the top few positions to the
   // landmarks.  The shuffle step means landmarks will appear in random
   // positions (instead of trees always appearing near the center), and
   // generating more candidates than needed means some of the eligible
   // positions would be unoccupied.  This is intended to avoid clustering
   // landmarks near large empty lots.
   #define TEST_POSITIONS  (LANDMARK_VARIATIONS * 2)
   XY candidates[TEST_POSITIONS];

   // Expansion happens in a hexagonal pattern, see demo in
   // hexagon_expansion.pl.
   int size = 1;
   int edge_step = 0;
   int side_step = 0;
   XY p = {LANDMARK_RADIUS * 2, 0};
   for(int count = 0; count < TEST_POSITIONS;)
   {
      // Accept landmark position if it will not obscure player's starting
      // position, and will not overlap with existing trader signs.
      if( (p.x < RESERVED_MIN_X || RESERVED_MAX_X < p.x ||
           p.y < RESERVED_MIN_Y || RESERVED_MAX_Y < p.y) &&
          !CheckForOverlap(trader_count, p.x, p.y, LANDMARK_RADIUS) )
      {
         candidates[count++] = p;
      }

      p.x += offset[side_step].x;
      p.y += offset[side_step].y;
      edge_step++;
      if( edge_step == size )
      {
         edge_step = 0;
         side_step++;
         if( side_step == 6 )
         {
            side_step = 0;
            size++;
            p.x += LANDMARK_RADIUS * 2;
         }
      }
   }
   #undef RESERVED_MIN_X
   #undef RESERVED_MIN_Y
   #undef RESERVED_MAX_X
   #undef RESERVED_MAX_Y

   // Shuffle candidate positions using Fisher-Yates shuffle.
   for(int i = TEST_POSITIONS - 1; i > 0; i--)
   {
      const int j = RAND(i);
      const XY t = candidates[i];
      candidates[i] = candidates[j];
      candidates[j] = t;
   }
   #undef TEST_POSITIONS

   // Assign landmark positions from top candidates.
   memcpy(landmark_positions, candidates, LANDMARK_VARIATIONS * sizeof(XY));
}
